platform :ios, '8.0'
target "YMTools" do
pod 'AFNetworking', '~> 3.0'
pod 'Masonry', '~> 0.6.3'
pod 'SDWebImage', '~> 3.7.3'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'IGListKit', '~> 3.0'
pod 'KVOController'
pod 'ChameleonFramework'
pod 'Onboard'
pod 'MJRefresh'
pod 'SocketRocket'
pod 'DZNEmptyDataSet'
pod 'Bugly'
pod 'YTKNetwork' , '~>2.0.4'
pod 'CYLTabBarController'
pod 'JPVideoPlayer'
pod 'GCDWebServer', '~>3.0'
pod 'GCDWebServer/WebUploader', '~> 3.0'
pod 'GCDWebServer/WebDAV', '~> 3.0'
pod 'TZImagePickerController'
pod 'RealReachability'
pod 'ReactiveCocoa', :git => 'https://github.com/zhao0/ReactiveCocoa.git', :tag => '2.5.2'
end
