# 第二行是为了保证公有库的正常使用
source 'https://gitee.com/Elv_Y/YMSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target "YMTools" do
pod 'AFNetworking', '~> 3.0'
pod 'Masonry', '~> 0.6.3'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'IGListKit', '~> 3.0'
pod 'KVOController'
pod 'ChameleonFramework'
pod 'Onboard'
pod 'MJRefresh'
pod 'SocketRocket'
pod 'DZNEmptyDataSet'
pod 'Bugly'
pod 'YTKNetwork' , '~>2.0.4'
pod 'CYLTabBarController'
pod 'GCDWebServer', '~>3.0'
pod 'GCDWebServer/WebUploader', '~> 3.0'
pod 'GCDWebServer/WebDAV', '~> 3.0'
pod 'TZImagePickerController'
pod 'RealReachability'
pod 'ReactiveCocoa','~>2.5'
pod 'DKNightVersion'
pod 'DoraemonKit/Core'
pod 'YMBase'
pod 'Realm'
pod 'SDWebImage'
pod 'MangoFix'
end
